
COMMAND cmds[]=
{
	{	"",				NULL								},
	{	"0",			NULL								},
	{	"1",			NULL								},
	{	"2",			NULL								},
	{	"3",			NULL								},
	
	{	"4",			NULL								},
	{	"5",			NULL								},
	{	"6",			NULL								},
	{	"7",			NULL								},
	{	"8",			NULL								},
	
	{	":",			(CMDF	*)	dummy			},
	{	"*",			(CMDF	*)	dummy			},
	{	">",			dosit								},
	{	".",			dosit								},
	{	"/",			dosit								},
	
	{	"AA",			aa									},
	{	"ALLOC",	allstuf							},
	{	"ALLFB",	allstuf							},
	{	"ALLST",	allstuf							},
	{	"APP",		filebuf							},
	
	{	"ASTAT",	filehands						},
	{	"BDN",		rbufs								},
	{	"BDP",		rbufs								},
	{	"BUF",		rbufs								},
	{	"C",			(CMDF	*)	c					},
	
	{	"CALL",		call								},
	{	"CAT",		strfuncs						},
	{	"CLALL",	filehands						},
	{	"CLOSE",	filehands						},
	{	"CLRCA",	(CMDF	*)	clrca			},
	
	{	"CLS",		(CMDF	*)	cls				},
	{	"COMP",		comp								},
	{	"COPY",		ren									},
	{	"CPY",		strfuncs						},
	{	"DEC",		mathfuncs						},
	
	{	"DEL",		del									},
	{	"DIR",		dir									},
	{	"DL",			dl									},
	{	"DN",			defdest							},
	{	"DP",			defdest							},
	
	{	"DRITE",	drite								},
	{	"DS",			(CMDF	*)	ds				},
	{	"DSUP",		(CMDF	*)	dsup			},
	{	"EDSTR",	edstrcmd						},
	{	"END",		(CMDF	*)	end				},
	
	{	"ER",			del									},
	{	"EX",			die									},
	{	"FREE",		dofree							},
	{	"FQ",			(CMDF	*)	fq				},
	{	"FRITE",	filehands						},
	
	{	"FSTAT",	filehands						},
	{	"GBUF",		filehands						},
	{	"GETXT",	getxtcmd						},
	{	"GO",			go									},
	{	"HELP",		help								},
	
	{	"?",			help								},
	{	"IF",			ifcond							},
	{	"IFE",		ife									},
	{	"IFEF",		filehands						},
	{	"IFG",		ififs								},
	
	{	"IFI",		ififs								},
	{	"IFO",		ifo									},
	{	"IFS",		ififs								},
	{	"IFT",		ift									},
	{	"IL",			il									},
	
	{	"INC",		mathfuncs						},
	{	"INTER",	(CMDF *) inter			},
	{	"INTRP",	intrp								},
	{	"KEY",		key									},
	{	"KL",			(CMDF	*)	kl				},
	
	{	"LD",			dir									},
	{	"LF",			lf									},
	{	"LOAD",		filebuf							},
	{	"LSCRN",	lscrn								},
	{	"LSTVS",	lscrn								},
	
	{	"LWR",		lwr									},
	{	"M",			(CMDF	*)	m					},
	{	"MO",			(CMDF	*)	mo				},
	{	"MOME",		mome								},
	{	"MOV",		mathfuncs						},
	
	{	"MSETH",	mseth								},
	{	"MV",			(CMDF	*)	mv				},
	{	"ON",			on									},
	{	"OPEN",		filehands						},
	{	"OPR",		mathfuncs						},
	
	{	"P",			pa									},
	{	"PBUF",		filehands						},
	{	"POP",		pushpop							},
	{	"PUSH",		pushpop							},
	{	"PUTXT",	putxtcmd						},
	
	{	"Q",			die									},
	{	"RDLN",		filehands						},
	{	"READ",		filehands						},
	{	"REALL",	allstuf							},
	{	"REDIR",	redir								},
	
	{	"REDSP",	(CMDF	*)	redsp			},
	{	"REM",		rem									},
	{	"REN",		ren									},
	{	"RET",		(CMDF	*)	ret				},
	{	"RITE",		rits								},
	
	{	"S",			sendf								},
	{	"SAVE",		filebuf							},
	{	"SCTRL",	sctrl								},
	{	"SEEK",		filehands						},
	{	"SETBF",	setbf								},
	
	{	"SETMP",	setmp								},
	{	"SETPR",	setpr								},
	{	"SFORM",	sform								},
	{	"SIZE",		size								},
	{	"SLEN",		slen								},
	
	{	"SMASK",	smask								},
	{	"SMAX",		smask								},
	{	"SO",			so									},
	{	"SPTR",		sptr								},
	{	"SRITE",	srite								},
	
	{	"STC",		strfuncs						},
	{	"STOFF",	(CMDF	*)	stoff			},
	{	"STON",		(CMDF	*)	ston			},
	{	"STST",		strfuncs						},
	{	"SUP",		(CMDF	*)	sup				},
	
	{	"TD",			(CMDF	*)	td				},
	{	"TELL",		filehands						},
	{	"UNCMP",	comp								},
	{	"UNDSP",	(CMDF	*)	dsup			},
	{	"UNSUP",	(CMDF	*)	sup				},
	
	{	"UPR",		upr									},
	{	"VTYPE",	vtype								},
	{	"W",			receive							},
	{	"XB",			xb									},
	{	"",				(CMDF	*)	reperror	}
};